# Generated by Django 4.1.7 on 2023-04-05 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 18, 36, 23, 585390)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 18, 36, 23, 584391)),
        ),
        migrations.AlterField(
            model_name='event',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 18, 36, 23, 584391)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='imgDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 18, 36, 23, 585390)),
        ),
    ]
